#spring.datasource.url=jdbc:mysql://localhost:3306/ToDo?serverTimezone=UTC&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=coderslab
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.javax.persistence.validation.mode=none

spring:
 datasource:
  url: "jdbc:mysql://localhost:3306/ToDo?serverTimezone=UTC&useSSL=false"
  username: "root"
  password: "coderslab"
 main:
  banner-mode: off
 jpa:
  properties:
   hibernate:
    dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
   javax:
    persistence:
     validation:
      mode: "none"
  show-sql: true
  hibernate:
   ddl-auto: "update"
task.template.allowMultipleTasks: false



